name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Bank Security Protocol Test
      id: bank-security-protocol-test
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Bank Security Protocol Test
        setup-command: ''
        command: javac src/*.java && java -cp src Main
        input: ''
        expected-output: |-
          Starting Balance: $100.0
          Error: Invalid deposit amount
          Error: Insufficient funds or invalid amount
          Final Balance: $130.0
        comparison-method: contains
        timeout: 2
        max-score: 100
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        BANK-SECURITY-PROTOCOL-TEST_RESULTS: "${{steps.bank-security-protocol-test.outputs.result}}"
      with:
        runners: bank-security-protocol-test
